add option to remove hypixel's lobby join messages
moehreag/AxolotlClient-branding pull request #110
Opened 2023-09-22 13:18 UTC by moehreag

- [ ] fix regexes

2023-11-28 15:16 UTC, TheKodeToad requested changes

2023-11-28 15:16 UTC, TheKodeToad commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +	private static final HypixelMessages Instance = new HypixelMessages();
```suggestion
	private static final HypixelMessages instance = new HypixelMessages();
```
not important but why not this?

2023-11-28 15:16 UTC, TheKodeToad commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				map.computeIfAbsent(entry.getKey(), s -> pattern);
```suggestion
				map.putIfAbsent(entry.getKey(), pattern);
```

2023-11-28 15:16 UTC, TheKodeToad commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
```suggestion
				messageLanguageMap.computeIfAbsent(entry.getKey(), s -> new HashMap<>()).put(lang, pattern);
```

2023-11-28 15:26 UTC, moehreag commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
.putIfAbsent returns the previous value, not the potentially new one

2023-11-28 16:25 UTC, TheKodeToad commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
nop

2023-11-28 16:27 UTC, TheKodeToad commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
![image](https://github.com/AxolotlClient/AxolotlClient-mod/assets/57493648/f2bf3310-8abc-42b8-81c8-99ebeaf539df)
it returns the same as get would

2023-11-28 17:17 UTC, DarkKronicle reviewed
Looks good after a quick glance. Can't see anything wrong.

2023-11-28 17:17 UTC, DarkKronicle commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +			JsonObject lines = GsonHelper.GSON.fromJson(new InputStreamReader(resource.getInputStream()), JsonObject.class);
Indentation is weird here

2023-11-28 17:17 UTC, DarkKronicle commented on 1.16_combat-6/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +			JsonObject lines = GsonHelper.GSON.fromJson(new InputStreamReader(resource.getInputStream()), JsonObject.class);
Indentation is also weird here

2023-11-28 18:16 UTC, moehreag commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
`putIfAbsent` has a different return value than `computeIfAbsent`, the latter returns the current (new) value while the former returns the previous (older) value

2023-11-29 22:58 UTC, TheKodeToad commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
why do you want the old value?

2023-11-29 23:02 UTC, moehreag commented on 1.16.5/src/main/java/io/github/axolotlclient/modules/hypixel/HypixelMessages.java
> +				messageLanguageMap.get(entry.getKey()).put(lang, pattern);
we don't, we want the potentially new value (the map of language to actual value) to add the value to it. The old value may potentially be `null`. This is the reason for a separated `.get` call.

2023-11-29 23:32 UTC, TheKodeToad approved these changes

2023-11-29 23:33 UTC, merged